from nula.models import blstm_seq_embed
BLSTMSequenceEmbed = blstm_seq_embed.BLSTMSequenceEmbed

from nula.models import blstm_seq_embed_wAttention
BLSTMSequenceEmbedwAttention = blstm_seq_embed_wAttention.BLSTMSequenceEmbedwAttention